endpoint: http://localhost:8080/blazegraph/sparql
output: './output'

graphsQuery: '
  PREFIX ldp: <http://www.w3.org/ns/ldp#>
  PREFIX Platform: <http://www.metaphacts.com/ontologies/platform#>
  SELECT DISTINCT ?g WHERE {  
    GRAPH ?g {
        Platform:formContainer ldp:contains ?container .
    }
  }
'

additionalGraphs:
 - http://www.metaphacts.com/ontologies/platform#formContainer/context
