version: "3"
services:
    backup:
        container_name: ${PROJECT_NAME}_graph_backup
        image: swissartresearx/graph-backup
        build: .
        restart: always
        volumes:
            - ./config:/config
            - ./${OUTPUT_FOLDER}:/output
        networks:
             - docker_network

networks:
  docker_network:
    name: ${DOCKER_NETWORK}
    external: true
