version: "3"
services:
    backup:
        container_name: ${PROJECT_NAME}_graph_backup
        image: swissartresearx/graph-backup
        build: .
        volumes:
            - ./config:/config
            - ./output:/output